name: TaskFlow CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Job 1 : Tests unitaires
  test:
    name: Tests unitaires
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installer les dépendances
        run: pip install -r requirements.txt

      - name: Lancer les tests
        run: pytest test_app.py -v

  # Job 2 : Build Docker (seulement si tests OK)
  build:
    name: Build Docker
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Build de l'image Docker
        run: docker build -t taskflow:${{ github.sha }} .

      - name: Vérifier l'image
        run: docker images taskflow

  # Job 3 : Scan de sécurité (seulement si build OK)
  security:
    name: Scan de sécurité
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Build de l'image
        run: docker build -t taskflow:latest .

      - name: Scan Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'taskflow:latest'
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'
